backend/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('usercreate/', views.usercreatefunc, name='usercreate'),
    path('login/', views.loginfunc, name='login'),
    path('logout/', views.logoutfunc, name='logout'),
    #path('<int:pk>', views.postcommentfunc, name='post_comment'),
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('post_detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'), 
    path('post_update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'), 
    path('post_delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'), 
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

backend/blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

    def __str__(self): # Post モデルが直接呼び出された時に返す値を定義
        return self.title # 記事タイトルを返す

class Comment(models.Model):
    #記事に対するコメント
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='対象記事')
    date = models.DateTimeField('作成日', default=timezone.now)
 
    def __str__(self):
        return self.text[:20]

backend/blog/forms.py
from django import forms
from .models import Post, Comment

# DjangoのModelFormでは強力なValidationを使える
class PostCreateForm(forms.ModelForm):

    class Meta:
        # Post モデルと接続し、Postモデルの内容に応じてformを作ってくれる
        model = Post
        # 入力するカラムを指定
        fields = ('title', 'text')

class CommentCreateForm(forms.ModelForm):
    #コメントフォーム
    class Meta:
        model = Comment
        exclude = ('target', 'date')

backend/blog/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import PostCreateForm, CommentCreateForm 
from .models import Post, Comment
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def usercreatefunc(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.create_user(username, '', password)
            return render(request, 'usercreate.html')
        except IntegrityError:
            return render(request, 'usercreate.html', {'error':'このユーザーはすでに登録されています'})
    return render(request, 'usercreate.html')

def loginfunc(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('blog:post_list')
        else:
            return render(request, 'login.html', {'context':'ログインできませんでした'})
    return render(request, 'login.html', {'context':'get method'})

def logoutfunc(request):
    logout(request)
    return redirect('blog:login')

#def postcommentfunc(request, pk):
#    #記事ページ
#    detail = get_object_or_404(Post, pk=pk)
#    context = {
#    "detail": detail,
#    "comments": Comment.objects.filter(target=detail.id)   #該当記事のコメントだけを渡す
#    }
#    return redirect('blog:post_list')


class PostListView(generic.ListView):
    template_name = 'post_list.html'
    model = Post

class PostCreateView(generic.CreateView):
    template_name = 'post_form.html'
    #作成したい model を指定
    model = Post
    # 作成した form クラスを指定
    form_class = PostCreateForm
    # 記事作成に成功した時のリダイレクト先を指定
    success_url = reverse_lazy('blog:post_list')

class PostDetailView(generic.DetailView):
    template_name = 'post_detail.html'
    model = Post
    def postdetail(request, pk):
       detail = get_object_or_404(Post, pk=pk)
       context = {
           "detail": detail,
           "comments": Comment.objects.filter(target=detail.id)   #該当記事のコメントだけを渡します。
       }


class PostUpdateView(generic.UpdateView):
    template_name = 'post_form.html'
    model = Post
    form_class = PostCreateForm 
    success_url = reverse_lazy('blog:post_detail')

class PostDeleteView(generic.DeleteView):
    template_name = 'post_confirm_delete.html'
    model = Post
    #削除をしてしまうとアクセス対象の記事がなくなってしまうので、詳細画面 (post_detail) にはリダイレクトさせない
    success_url = reverse_lazy('blog:post_list')

class CommentCreate(generic.CreateView):
    #コメント投稿ページのビュー
    template_name = 'comment_form.html'
    model = Comment
    form_class = CommentCreateForm
 
    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Post, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context

backend/templates/base.html
<!doctype html>
<html lang="ja">
<head>
    <title>kazama のブログ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">トップ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_create' %}">投稿</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- このblockの中で各templateの記載内容が呼び出される -->
    {% block content %} 
    {% endblock %}      
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>

backend/templates/comment_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <span class="helptext">※{{ field.help_text }}</span>
            {% endif %}
            {{ field.errors }}
        </div>
    {% endfor %}
    {% csrf_token %}

    <button type="submit" class="btn-link">送信</button>
    <a class="button btn-link" href="{% url 'blog:post_detail' post.pk %}">送信せずに戻る</a>
</form>

<!--<p>{{ post.title }}</p>
<form action="" method="POST" id="comment-form">
    <table class="table">
        <tr>
          <th>名前</th>
          <td>{{ form.name }}</td>
        </tr>
        <tr>
          <th>コメント</th>
          <td>{{ form.text }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-link">送信</button>
    <a href="{% url 'blog:post_detail' post.pk %}">送信せずに戻る</a>
    {% csrf_token %}
</form>
-->
<!--
<div class="container col-lg-6 offset-lg-3">
    <p class="titleline">{{ post.title }}</p>
    <form action="" method="POST" id="comment-form">
      {{ form.non_field_errors }}
      {% for field in form %}
      <div class="field">
        {{ field.label_tag }}
   
        {{ field.errors }}
      </div>
      {% endfor %}
      {% csrf_token %}
      <div class="row my-3">
        <button type="submit" class="btn btn-success col-3 offset-2">投稿する</button>
        <a class="btn btn-danger col-3 offset-2" href="{% url 'blog:post_detail' post.pk %}">キャンセル</a>
      </div>
    </form>
  </div>
  -->
{% endblock %}

backend/templates/index.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    {% if user.id  %}
    <p>ログインしました．</p>
    <p>こんにちは，{{ user.username }}さん</p>
    <a href="{% url 'logout' %}">ログアウトする</a>
    {% else %}
    <a href="{% url 'login' %}">ログイン</a>
    <a href="{% url 'create_account' %}">アカウント作成</a>
    {% endif %}
  </body>
</html>

backend/templates/login.html
{% extends 'base.html' %}

{% block content %}
<body class="text-center">
    {{ context }}
    <form class="form-signin" method="POST">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">ログインする</h1>
        <label for="inputEmail" class="visually-hidden">ユーザー名</label>
        <input type="text" id="inputEmail" class="form-control" placeholder="username" name='username' required autofocus>
        <label for="inputPassword" class="visually-hidden">パスワード</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" name='password' required>
        <button class="w-100 btn btn-lg btn-primary" type="submit">ログイン</button>
    </form>
</body>
{% endblock %}

backend/templates/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    <table>
        <tr>
          <th>タイトル</th>
          <td>{{ post.title }}</td>
        </tr>
        <tr>
          <th>本文</th>
          <td>{{ post.text }}</td>
        </tr>
        <tr>
          <th>日付</th>
          <td>{{ post.date }}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

backend/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<table>
    <tr>
      <th>タイトル</th>
      <td>{{ post.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <!-- linebreaksbk を入れると改行タグでちゃんと改行して表示されるようになる -->
      <td>{{ post.text | linebreaksbr}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ post.date }}</td>
    </tr>
    <!--{% for comment in comments %}
    <div class='border-bottom'>{{ comment.name }}　{{ comment.created_at }}</div><div class='mt-2'>{{ comment.text }}</div>
    {% endfor %}
    -->
</table>
<a href="{% url 'blog:comment_create' post.pk %}">コメントする</a>

{% endblock %}

backend/templates/post_form.html
{% extends 'base.html' %}

{% block content %}
<p>{{ post.title }}</p>
<form action="" method="POST">
    <table class="table">
        <tr>
          <th>タイトル</th>
          <td>{{ form.title }}</td>
        </tr>
        <tr>
          <th>本文</th>
          <td>{{ form.text }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

backend/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
    </tr>
  </thead>
  <tbody>
    {% for post in post_list %}
    <tr>
      <!-- 「url 'アプリ名:逆引きURL' 渡されるモデル.pk」 という描き方 -->
      <td><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></td>
      <td>{{ post.date }}</td>
      <td>
        <!-- superuserでログインしている時にのみ表示 -->
        {% if user.is_superuser %}
        <!-- HTMLを アプリ名_モデル名_change にすると admin でそのまま編集できる -->
          <a href="{% url 'blog:post_update' post.pk %}">編集</a>
        {% endif %}
      </td>
      <td>
        {% if user.is_superuser %}
          <a href="{% url 'blog:post_delete' post.pk %}">削除</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
    <a href="{% url 'blog:logout' %}">ログアウト</a>
  </tbody>
</table>

{% endblock %}

backend/templates/usercreate.html
<body class="text-center">
    {{ error }}
    <form class="form-signin" method="POST">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">ユーザー登録する</h1>
        <label for="inputEmail" class="visually-hidden">ユーザー名</label>
        <input type="text" id="inputEmail" class="form-control" placeholder="username" name='username' required autofocus>
        <label for="inputPassword" class="visually-hidden">パスワード</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" name='password' required>
        <button class="w-100 btn btn-lg btn-primary" type="submit">登録</button>
    </form>
</body>